### PR TITLE
refactor: auth refreshToken dtos refactor

### PR DESCRIPTION
**Pull request by sivanpayyadakath**
auth refreshToken DTOs refactor

### CODE REVIEW

**Review by yashmurty — APPROVED** [review]
LGTM! :tada: 

@asad-mlbd I think we just made some minor name changes in this PR.

**Comment by asad-mlbd** [comment]
Just one thought @yashmurty @sivanpayyadakath, to keep the output DTO naming convention - is it be better to use `AuthTokenOutput` instead of `AuthToken`?

**Review by asad-mlbd — APPROVED** [review]
@sivanpayyadakath my only suggestion is maybe we can use naming `AuthTokenOutput`. Otherwise LGTM

**Comment by sivanpayyadakath** [comment]
@asad-mlbd 
Thank you for the review . Yes, `AuthTokenOutput` is more appropriate . 👍

**Review by yashmurty — APPROVED** [review]
LGTM! 🎉

**Pull request merged**
